name: Push on Docker

on: 
  push:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: [self-hosted]
    
    steps:
      - name: Name  of first step
        uses: docker/setup-buildx-action@v3

      - name: Login in Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push in Docker Hub
        uses: docker/build-push-action@v5
        with:
          push: true
          tag: parandzem/some-repo:latest
            
        

      
